@startuml
class Inventory {
  - _instance: Inventory
  - items: dict[object, int]
  - name: str
  + get_instance(): object | None
  + add_item(item, quantity)
  + set_name(name: str): str
  + __str__(): str
}

Inventory ..> Inventory : _instance
@enduml


