@startuml

interface Observer {
    +update(subject: Observable)
}

class Observable {
    -observers: List<Observer>
    +attach(observer: Observer)
    +detach(observer: Observer)
    +notify(message: String)
}

class Supplier implements Observer {
    -items_to_supply: Dict[String, Item]
    +update(subject: Observable)
    +supply(items: Dict[String, Item])
    +add_item(item: Item)
}

class Manager implements Observer {
    -cash: Int
    +update(subject: Observable)
    +sell(amount: Int): Int
    +buy(amount: Int): Int
}

Observable "1" o-- "0..*" Observer : notifies >




@enduml
