@startuml
interface PricingStrategy {
    +get_price(base_price: float): float
}

class RegularPrice {
    +get_price(base_price: float): float
}

class DiscountPrice {
    +get_price(base_price: float): float
}

class SpecialOfferPrice {
    +get_price(base_price: float): float
}

class SingleItem {
    -pricing_strategy: PricingStrategy
    +set_price(price: float): SingleItem
    +get_price(): float
}

PricingStrategy <|-down- RegularPrice
PricingStrategy <|-down- DiscountPrice
PricingStrategy <|-down- SpecialOfferPrice

SingleItem o-- PricingStrategy
@enduml
